builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
archive:
  replacements:
    darwin: Darwin
    linux: Linux
  files:
    - LICENSE
    - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
